name: Secret Test Workflow

on:
  # Allow manual triggering
  workflow_dispatch:

env:
  SECRET_TEST: ${{ secrets.SECRET_TEST }}
  SECRET_TEST_STRING: '{"key": "${{ secrets.SECRET_TEST }}"}'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run first job
        run: echo "SECRET_TEST_STRING=${{ env.SECRET_TEST_STRING }}"

